image: node:latest

variables:
  BUILD_DIR:    'dist/'
  LIVE_DIR:     '/subs/klaviertrio'
  STAGING_DIR:  '/staging'

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install -g gulp
    - npm install
    - gulp build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - "$BUILD_DIR"
    expire_in: 15 mins

deploy_prod:
  stage: deploy
  only:
    - master
  script:
    - apt-get update
    - apt-get install lftp
    - lftp -e "mirror -R $BUILD_DIR $LIVE_DIR" -u $NAME,$PASS $HOST
  environment:
    name: production